# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e57f759d40be780acfc45add729cac53"
name = "pod-generator-dtf-public-1"
application_url = "https://pod-app-nu.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://pod-app-nu.vercel.app/auth/callback",
  "https://pod-app-nu.vercel.app/auth/login"
]
